// auth
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_STORE = 'CLEAR_STORE';
export const BACK_TO_REGISTER = 'BACK_TO_REGISTER';

// admin
export const ADMIN_ADD_COMPANY = 'ADMIN_ADD_COMPANY';
export const ADMIN_ADD_STORY = 'ADMIN_ADD_STORY';
export const ADMIN_GET_COMPANY = 'ADMIN_GET_COMPANY';
export const ADMIN_GET_COMPANY_BY_ID = 'ADMIN_GET_COMPANY_BY_ID';
export const ADMIN_GET_STORY = 'ADMIN_GET_STORY';
export const ADMIN_DELETE_COMPANY = 'ADMIN_DELETE_COMPANY';
export const ADMIN_DELETE_STORY = 'ADMIN_DELETE_STORY';
export const ADMIN_ERROR = 'ADMIN_ERROR';

// director
export const DIRECTOR_GET_COMPANY = 'DIRECTOR_GET_COMPANY';
export const DIRECTOR_GET_STORY = 'DIRECTOR_GET_STORY';
