export { default as AppBugReports } from './IjaradagilarCard';
export { default as AppConversionRates } from './IjaradagilarChart';
// export { default as AppCurrentSubject } from './AppCurrentSubject';
export { default as StudentDistributionChart } from '../../../tutor/charts/StudentDistributionChart';
export { default as AppItemOrders } from './ImtiyozCard';
export { default as AppNewsUpdate } from './AppNewsUpdate';
export { default as AppNewUsers } from './TalabalarSoniCard';
export { default as AppOrderTimeline } from './AppOrderTimeline';
export { default as AppTasks } from './AppTasks';
// export { default as AppTrafficBySite } from './AppTrafficBySite';
export { default as AppWebsiteVisits } from './PulTulanganlarChart';
export { default as AppWeeklySales } from './GruhlarSoniCard';
export { default as UydagilarCard } from './UydagilarCard';
export { default as YotoqxonaCard } from './YotoqxonaCard';
